### ISSUE TITLE
remove pywapi-0.3.8?

### ISSUE THREAD

**Issue by hunkim** [shivanggupta/Wit-Facebook-Py#1]
I would remove pywapi-0.3.8, since it may update later. You can use pip to install.

**Comment by shivanggupta** [comment]
Ideally that would be the case, but this repo has been set up for Heroku and as pywapi-0.3.8 is not supported on the pip there, this is the easiest way to install it on the remote server. 
pywapi is only used for demo here and I intend to replace it with a more efficient API. Perhaps from DarkSky.
