### ISSUE TITLE
This sends a message to FB back?

### ISSUE THREAD

**Issue by hunkim** [shivanggupta/Wit-Facebook-Py#2]
I don't see the FB message back part. 

Also, if you can avoid the global variable, it would be best.

```
if done:
                    print messageToSend
                    bot.send_text_message(recipient_id, messageToSend)
```

**Comment by shivanggupta** [comment]
Yes that global variable is a problem, I am still figuring out a solution for that as the function prototypes are defined in external libraries and I cannot modify those. The 'done' variable is also not needed, but it doesn't seem to work without it. Still figuring that out. 

The third line of the code block above sends the message back to Facebook. 
`bot.send_text_message(recipient_id, messageToSend)`

**Comment by hunkim** [comment]
I see. you are using pymessenger.
